### PR TITLE
Fixes compile error in Rust 1.38

### LINKED ISSUE #7: Compile error: use of unstable library feature 'unicode_internals'
```
error[E0658]: use of unstable library feature 'unicode_internals'
   --> src/fmt_macros.rs:422:34
    |
422 |             Some(&(pos, c)) if c.is_xid_start() => {
    |                                  ^^^^^^^^^^^^
    |
    = help: add `#![feature(unicode_internals)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'unicode_internals'
   --> src/fmt_macros.rs:431:18
    |
431 |             if c.is_xid_continue() {
    |                  ^^^^^^^^^^^^^^^
    |
    = help: add `#![feature(unicode_internals)]` to the crate attributes to enable

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `runtime-fmt`.
```

I'll provide a PR shortly.

### PR DESCRIPTION
**Pull request by leenozara**
Added `feature(unicode_internals)`.
Removed old features.
Added `dyn` keyword where needed.

@SpaceManiac This crate fails to compile with 1.38. It is used on the https://riker.rs framework - can you review this PR and publish an update so that we can also compile.

Thank you.

---

ed. Fixes #7

### CODE REVIEW

**Comment by leenozara** [comment]
Test fail due to these two lines (marked edge cases):

https://github.com/leenozara/runtime-fmt/blob/54caebe51d47e304893999cd209fb7faedd585d7/tests/ifmt.rs#L182

**Comment by SpaceManiac** [comment]
Thanks for the pull request. The diff looks good; I will test locally and publish a release when able.

**Review by SpaceManiac — APPROVED** [review]
